### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by victorjoaoss** [PetJournal/petjournal.web#2]
https://github.com/PetJournal/product/issues/1

**Comment by leottx** [comment]
## Tarefas
**Estrutura e estilização do formulário de login:**
- [x] Adicionar o campo de email/telefone
- [x] Adicionar o campo de senha
- [x] Adicionar o checkbox para salvar o login
- [x] Adicionar o link para página de redefinição de senha
- [x] Adicionar o botão de submissão do formulário
- [x] Adicionar o link para página de cadastro

**Validações:**
  - [x] Validar o campo de email/telefone enquanto o usuário preenche.
  - [x] Validar o campo de senha enquanto o usuário preenche
  - [x] Exibir uma mensagem de erro se as credenciais submetidas forem incorretas

**Comment by leottx** [comment]
Essa task foi concluída usando dados mocados, pois até então não haviam concluído o backend.

Sendo assim, ainda falta essa integração para o que o time de QA possa validar.
