### ISSUE TITLE
Cadastro do Usuário

### ISSUE THREAD

**Issue by victorjoaoss** [PetJournal/petjournal.web#3]
https://github.com/PetJournal/petjournal.product/issues/2

**Comment by leottx** [comment]
Essa tarefa foi realizada utilizando dados mockados, pois até então o backend ainda não estava pronto.

Sendo assim, agora falta a integração com o backend.

Na reunião de hoje, 12/06/2023, o time de produto ficou de criar uma nova coluna para tarefas com bloqueio como é o caso dessa.
